name: jax_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0
  - asttokens=3.0.0
  - Brotli=1.0.9
  - chex=0.1.89
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.11.0
  - debugpy=1.8.13
  - decorator=5.2.1
  - equinox=0.11.10
  - etils=1.5.2
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.55.3
  - importlib_metadata=8.6.1
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipympl=0.9.7
  - ipython=8.18.1
  - ipywidgets=8.1.6
  - jax=0.4.30
  - jax-cuda12-pjrt=0.4.30
  - jax-cuda12-plugin=0.4.30
  - jaxlib=0.4.30
  - jaxtyping=0.2.36
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.14
  - kiwisolver=1.4.4
  - matplotlib=3.9.2
  - matplotlib-inline=0.1.7
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mkl-service=2.4.0
  - ml_dtypes=0.5.1
  - mpi4py=4.0.0
  - nest_asyncio=1.6.0
  - numpy=2.0.2
  - nvidia-cublas-cu12=12.8.4.1
  - nvidia-cuda-cupti-cu12=12.8.90
  - nvidia-cuda-nvcc-cu12=12.8.93
  - nvidia-cuda-runtime-cu12=12.8.90
  - nvidia-cudnn-cu12=9.8.0.87
  - nvidia-cufft-cu12=11.3.3.83
  - nvidia-cusolver-cu12=11.7.3.90
  - nvidia-cusparse-cu12=12.5.8.93
  - nvidia-nccl-cu12=2.25.1
  - nvidia-nvjitlink-cu12=12.8.93
  - opt_einsum=3.4.0
  - optax=0.2.4
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.7
  - prompt_toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - Pygments=2.19.1
  - pyparsing=3.2.0
  - PyQt6=6.7.1
  - PyQt6_sip=13.9.1
  - python-dateutil=2.9.0.post0
  - PyYAML=6.0.2
  - pyzmq=26.2.0
  - scipy=1.13.1
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.16.0
  - stack_data=0.6.3
  - tomli=2.0.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - zipp=3.21.0