# config/fbpinn.yaml
# choose the model
model_type: "pinn"  # pinn/fbpinn

# choose the problem
pde: "problems.SineX6ODE"   # which physics module, define the problem in physics/problem.py
# training config
training:
  steps: 50000
  lr: 0.001
  checkpoint_every: None
# FBPINN
  n_sub: 2
  overlap: 1
  n_points_per_subdomain: 500
# PINN
# mini-batch param, only for pinn, not necessary for fbpinn
  n_collocation_points: 600
  batch_size: 100     
  shuffle: true #shuffle every epoch

mlp:
  in_size: 1
  out_size: 1
  width_size: 128
  depth: 5
  activation: "tanh"   

save:
  output_dir: "outputs/outputs_PINN_SinX6ODE"
  checkpoint_every: 0
